In [6]:
from IPython.utils import io
import pandas as pd
import os
from pathlib import Path
from matplotlib import pyplot as plt
from scipy.signal import find_peaks
import numpy as np
import seaborn as sns
import time
import joblib
from os.path import exists
import shutil
import sys
import time

from sklearn.model_selection import train_test_split
#From my EEG package 
import run_expts

#Let me see as many results as I want to see
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [7]:
clf_list = ['Rocket', 'HIVECOTE2', 'C_I_F', 'Dr_C_I_F', 'Inception_Time']

#Results dictionary structure : {model : {expt_type : {folder : results_df }}}
results_dict = {}
for clf in clf_list:
    results_dict[clf] = {1 : {} , 2 : {}}

core_path = '/export/sphere/ebirah/ko20929/RBD_files/notebooks/frequency_analysis/constructed_data/band_power_time_series/expt_dfs/'

folders = ['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files', 'REM_19_expt_files', 'EC_8_expts',
           'N1_full_expts', 'N2_full_expts', 'N3_full_expts', 'REM_full_expts', 'EC_full_expts']

files_not_found = []

for num in [1,2]:
    for folder in folders:
        for clf in clf_list:
            try:
                save_path = 'Results/' + clf + 'expt_type_' + str(num) + '_' + folder + 'int_df.h5'
                results_df = pd.read_hdf(save_path , key='df', mode='r')
            except FileNotFoundError:
                files_not_found.append(save_path)
                continue
                
            res_df = run_expts.generate_subset_acc_std(results_df, return_df = True)           
            results_dict[clf][num][folder] = res_df

In [9]:
# print(list(results_dict['Rocket'][1].keys() ))
for clf in clf_list:
    print(clf)
    for num in [1,2]:
        print('Expt Type: ' + str(num))
        not_displayed = []
        for key in list(results_dict[clf][num].keys() ):
            df = results_dict[clf][num][key].copy()
            cols_to_drop = [col for col in df.columns if df[col].mean() < 0.75]
            df = df.drop(cols_to_drop, axis = 1 )
            if len(df.columns) < 2:
                not_displayed.append(key)
                continue
            print(key)
            display(df)
        print(not_displayed)

Rocket
Expt Type: 1
N1_full_expts

   random_state  Right Central_Rocket_acc  Left Temporal_Rocket_acc
0            13                  0.803333                  0.728889
1            37                  0.778333                  0.825556

['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files', 'REM_19_expt_files', 'EC_8_expts', 'N2_full_expts', 'N3_full_expts', 'REM_full_expts', 'EC_full_expts']
Expt Type: 2
['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files', 'REM_19_expt_files', 'EC_8_expts', 'N1_full_expts', 'N2_full_expts', 'N3_full_expts', 'REM_full_expts', 'EC_full_expts']
HIVECOTE2
Expt Type: 1
N1_full_expts

,random_state,Frontal_HIVECOTE2_acc,Left Frontal_HIVECOTE2_acc,Right Frontal_HIVECOTE2_acc,Left Central_HIVECOTE2_acc,Right Central_HIVECOTE2_acc,Left Temporal_HIVECOTE2_acc,Right Temporal_HIVECOTE2_acc,Parietal_HIVECOTE2_acc,Left Parietal_HIVECOTE2_acc,Occipital_HIVECOTE2_acc
0,13,0.805556,0.788333,0.711111,0.826111,0.806111,0.828889,0.808333,0.828333,0.800556,0.786111
1,37,0.733333,0.733333,0.803333,0.780556,0.760556,0.805556,0.733333,0.753333,0.753333,0.778333

['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files', 'REM_19_expt_files', 'EC_8_expts', 'N2_full_expts', 'N3_full_expts', 'REM_full_expts', 'EC_full_expts']
Expt Type: 2
['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files', 'REM_19_expt_files', 'EC_8_expts', 'N1_full_expts', 'N2_full_expts', 'N3_full_expts', 'REM_full_expts', 'EC_full_expts']
C_I_F
Expt Type: 1
EC_8_expts

   random_state  Occipital_C_I_F_acc
0            13                 0.88
1            37                 0.84

['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files', 'REM_19_expt_files', 'N1_full_expts', 'N2_full_expts', 'N3_full_expts', 'REM_full_expts', 'EC_full_expts']
Expt Type: 2
['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files', 'REM_19_expt_files', 'EC_8_expts', 'N1_full_expts', 'N2_full_expts', 'N3_full_expts', 'REM_full_expts', 'EC_full_expts']
Dr_C_I_F
Expt Type: 1
EC_8_expts

   random_state  Occipital_Dr_C_I_F_acc
0            13                    0.84
1            37                    0.80

['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files', 'REM_19_expt_files', 'N1_full_expts', 'N2_full_expts', 'N3_full_expts', 'REM_full_expts', 'EC_full_expts']
Expt Type: 2
['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files', 'REM_19_expt_files', 'EC_8_expts', 'N1_full_expts', 'N2_full_expts', 'N3_full_expts', 'REM_full_expts', 'EC_full_expts']
Inception_Time
Expt Type: 1
['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files']
Expt Type: 2
['N1_customised_40_expt_files', 'N2_120_expt_files_v2', 'N3_82_expt_files']