In [1]:
import pandas as pd
import mne as mne
import os 
import time
import numpy as np
import matplotlib.pyplot as plt
import joblib
import constants
from IPython.utils import io
import time
import sys
import yasa
from scipy.signal import welch

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GroupShuffleSplit


from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier

#Import my modules
import format_eeg_data
import constants
import eeg_stat_ts
import run_expts

from scipy import stats
import scikit_posthocs as sp

# Using Load results 1 as a base - here I load all of the results to create necessary tables and do statistical significance tests
import calculate_results #This module will help me to calculate the per fold metrics

# Set display options to show all rows and columns
pd.set_option('display.max_rows', 50)  # Show rows
pd.set_option('display.max_columns', 160)  # Show columns

/user/home/ko20929/.conda/envs/sktime_latest/lib/python3.11/site-packages/antropy/fractal.py:197: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @jit((types.Array(types.float64, 1, "C", readonly=True), types.int32))
/user/home/ko20929/.conda/envs/sktime_latest/lib/python3.11/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package yasa is out of date. Your version is 0.6.3, the latest is 0.6.4.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
stat_feats_dict = joblib.load('statistical_features_results_dict.pkl')
pli_feats_dict = joblib.load('pli_best_results_dict.pkl')
combined_feats_dict = joblib.load('combined_best_results_dict.pkl')

In [13]:
stat_feats_dict

{'REM': {'acc': array([0.75 , 0.375, 0.5  , 1.   , 0.5  , 0.75 , 0.5  , 0.875, 0.625,
         0.5  ]),
  'prec': array([0.5       , 0.33333333, 0.        , 1.        , 0.        ,
         0.        , 0.66666667, 1.        , 0.        , 0.        ]),
  'recall': array([0.5       , 0.66666667, 0.        , 1.        , 0.        ,
         0.        , 0.4       , 0.5       , 0.        , 0.        ])},
 'N1': {'acc': array([0.75 , 0.875, 0.75 , 0.75 , 0.875, 0.875, 0.875, 0.5  , 0.75 ,
         0.75 ]),
  'prec': array([0.        , 1.        , 1.        , 0.66666667, 0.5       ,
         0.        , 1.        , 0.33333333, 1.        , 0.66666667]),
  'recall': array([0.        , 0.8       , 0.5       , 0.66666667, 1.        ,
         0.        , 0.75      , 0.33333333, 0.5       , 0.66666667])},
 'N2': {'acc': array([0.88888889, 0.5       , 0.5       , 0.25      , 0.75      ,
         0.77777778, 0.375     , 0.5       , 0.625     , 0.625     ]),
  'prec': array([0.5       , 0.        , 0.        , 0.        , 0.33333333,
         0.5       , 0.5       , 0.        , 0.        , 0.5       ]),
  'recall': array([1.        , 0.        , 0.        , 0.        , 1.        ,
         0.5       , 0.2       , 0.        , 0.        , 0.33333333])},
 'N3': {'acc': array([0.77777778, 0.625     , 0.375     , 0.125     , 0.75      ,
         0.66666667, 0.375     , 0.75      , 0.875     , 0.75      ]),
  'prec': array([0.33333333, 0.66666667, 0.375     , 0.        , 0.33333333,
         0.        , 0.        , 1.        , 0.66666667, 1.        ]),
  'recall': array([1.        , 0.5       , 1.        , 0.        , 1.        ,
         0.        , 0.        , 0.33333333, 1.        , 0.33333333])},
 'Wake': {'acc': array([1.        , 1.        , 0.66666667, 0.66666667, 0.66666667,
         1.        , 0.66666667, 0.5       , 0.83333333, 0.83333333]),
  'prec': array([1. , 1. , 0.5, 1. , 0. , 1. , 1. , 0. , 0.5, 1. ]),
  'recall': array([1.        , 1.        , 0.5       , 0.33333333, 0.        ,
         1.        , 0.33333333, 0.        , 1.        , 0.66666667])}}

In [3]:
combined_feats_dict['REM'].keys()
['acc', 'prec', 'recall']

['acc', 'prec', 'recall']

In [4]:
pli_feats_dict['REM']['acc']

array([0.5  , 0.75 , 0.75 , 0.75 , 0.375, 0.75 , 0.625, 0.5  , 0.625,
       0.75 ])

In [52]:
metrics = ['acc', 'prec', 'recall']
metric = 'prec'
# metric = 'acc'
#1. generate the dfs 
eeg_type_distribution = {}

name_list = []

for eeg_type in stat_feats_dict.keys():
    eeg_type_distribution['stat_only' + eeg_type] = stat_feats_dict[eeg_type][metric]
    name_list.append('stat_only' + eeg_type)

for eeg_type in pli_feats_dict.keys():
    eeg_type_distribution['pli_only' + eeg_type] = pli_feats_dict[eeg_type][metric]
    name_list.append('pli_only' + eeg_type)
    
for eeg_type in combined_feats_dict.keys():
    eeg_type_distribution['combined' + eeg_type] = combined_feats_dict[eeg_type][metric]
    name_list.append('combined' + eeg_type)

eeg_type_dist = pd.DataFrame(eeg_type_distribution)

In [45]:
[ 'stat_onlyN1', 'stat_onlyWake', 'pli_onlyN1', 'combinedWake' ]

['stat_onlyN1', 'stat_onlyWake', 'pli_onlyN1', 'combinedWake']

In [53]:
eeg_type_dist[[ 'combinedN1', 'stat_onlyN1', 'stat_onlyWake', 'pli_onlyN1', 'combinedWake' ]]

   combinedN1  stat_onlyN1  stat_onlyWake  pli_onlyN1  combinedWake
0    1.000000     0.000000            1.0       0.625          1.00
1    1.000000     1.000000            1.0       0.875          0.75
2    1.000000     1.000000            0.5       0.875          1.00
3    1.000000     0.666667            1.0       1.000          1.00
4    0.000000     0.500000            0.0       0.875          0.00
5    1.000000     0.000000            1.0       0.875          1.00
6    1.000000     1.000000            1.0       1.000          1.00
7    1.000000     0.333333            0.0       0.875          0.00
8    1.000000     1.000000            0.5       0.750          0.50
9    0.666667     0.666667            1.0       0.875          1.00

In [54]:
eeg_type_dist

,stat_onlyREM,stat_onlyN1,stat_onlyN2,stat_onlyN3,stat_onlyWake,pli_onlyREM,pli_onlyN1,pli_onlyN2,pli_onlyN3,pli_onlyWake,combinedREM,combinedN1,combinedN2,combinedN3,combinedWake
0,0.500000,0.000000,0.500000,0.333333,1.0,0.500,0.625,0.777778,0.444444,0.666667,0.250000,1.000000,0.250000,0.000000,1.00
1,0.333333,1.000000,0.000000,0.666667,1.0,0.750,0.875,0.750000,0.875000,0.666667,0.666667,1.000000,1.000000,1.000000,0.75
2,0.000000,1.000000,0.000000,0.375000,0.5,0.750,0.875,0.750000,0.625000,0.666667,0.333333,1.000000,1.000000,1.000000,1.00
3,1.000000,0.666667,0.000000,0.000000,1.0,0.750,1.000,0.500000,0.375000,0.333333,0.500000,1.000000,0.833333,0.666667,1.00
4,0.000000,0.500000,0.333333,0.333333,0.0,0.375,0.875,0.750000,0.875000,0.666667,0.000000,0.000000,0.333333,0.500000,0.00
5,0.000000,0.000000,0.500000,0.000000,1.0,0.750,0.875,0.666667,0.777778,0.666667,0.333333,1.000000,0.333333,0.000000,1.00
6,0.666667,1.000000,0.500000,0.000000,1.0,0.625,1.000,0.500000,0.500000,0.500000,0.750000,1.000000,1.000000,1.000000,1.00
7,1.000000,0.333333,0.000000,1.000000,0.0,0.500,0.875,0.750000,0.625000,0.166667,1.000000,1.000000,0.750000,0.000000,0.00
8,0.000000,1.000000,0.000000,0.666667,0.5,0.625,0.750,0.750000,0.625000,0.666667,1.000000,1.000000,1.000000,1.000000,0.50
9,0.000000,0.666667,0.500000,1.000000,1.0,0.750,0.875,0.500000,0.750000,0.666667,1.000000,0.666667,0.000000,0.000000,1.00

In [55]:
eeg_type_dist.mean()

stat_onlyREM     0.350000
stat_onlyN1      0.616667
stat_onlyN2      0.233333
stat_onlyN3      0.437500
stat_onlyWake    0.700000
pli_onlyREM      0.637500
pli_onlyN1       0.862500
pli_onlyN2       0.669444
pli_onlyN3       0.647222
pli_onlyWake     0.566667
combinedREM      0.583333
combinedN1       0.866667
combinedN2       0.650000
combinedN3       0.516667
combinedWake     0.725000
dtype: float64

In [37]:
data.T.shape

(10, 3)

In [38]:
eeg_type_dist.values.shape

(10, 15)

In [39]:
print(stats.friedmanchisquare(*eeg_type_dist.T.values) ) 
# output_results = sp.posthoc_nemenyi_friedman(eeg_type_dist.values)
output_results = sp.posthoc_nemenyi_friedman(eeg_type_dist.values)

FriedmanchisquareResult(statistic=22.980922098569195, pvalue=0.06058086532205505)

In [58]:
# Function to check if any two columns are the same
def check_identical_columns(df):
    columns = df.columns
    n = len(columns)
    identical_columns = []

    for i in range(n):
        for j in range(i + 1, n):
            if df[columns[i]].equals(df[columns[j]]):
                identical_columns.append((columns[i], columns[j]))

    return identical_columns

check_identical_columns(eeg_type_dist)

[('stat_onlyREM', 'lel')]

In [59]:
eeg_type_dist['lel'] = eeg_type_dist['stat_onlyREM']

In [40]:
output_results

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1.000000,0.9,0.900000,0.9,0.900000,0.90000,0.336950,0.9,0.90000,0.9,0.9,0.444911,0.900000,0.900000,0.641490
1,0.900000,1.0,0.900000,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
2,0.900000,0.9,1.000000,0.9,0.770198,0.90000,0.143439,0.9,0.90000,0.9,0.9,0.208068,0.866728,0.900000,0.390316
3,0.900000,0.9,0.900000,1.0,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
4,0.900000,0.9,0.770198,0.9,1.000000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
5,0.900000,0.9,0.900000,0.9,0.900000,1.00000,0.850640,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
6,0.336950,0.9,0.143439,0.9,0.900000,0.85064,1.000000,0.9,0.83455,0.9,0.9,0.900000,0.900000,0.561045,0.900000
7,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.900000,1.0,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
8,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.834550,0.9,1.00000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
9,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.900000,0.9,0.90000,1.0,0.9,0.900000,0.900000,0.900000,0.900000
10,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,1.0,0.900000,0.900000,0.900000,0.900000
11,0.444911,0.9,0.208068,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,1.000000,0.900000,0.657574,0.900000
12,0.900000,0.9,0.866728,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,1.000000,0.900000,0.900000
13,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.561045,0.9,0.90000,0.9,0.9,0.657574,0.900000,1.000000,0.850640
14,0.641490,0.9,0.390316,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.850640,1.000000

In [33]:
eeg_type_dist.values.T

array([[0.5       , 0.66666667, 0.        , 1.        , 0.        ,
        0.        , 0.4       , 0.5       , 0.        , 0.        ],
       [0.        , 0.8       , 0.5       , 0.66666667, 1.        ,
        0.        , 0.75      , 0.33333333, 0.5       , 0.66666667],
       [1.        , 0.        , 0.        , 0.        , 1.        ,
        0.5       , 0.2       , 0.        , 0.        , 0.33333333],
       [1.        , 0.5       , 1.        , 0.        , 1.        ,
        0.        , 0.        , 0.33333333, 1.        , 0.33333333],
       [1.        , 1.        , 0.5       , 0.33333333, 0.        ,
        1.        , 0.33333333, 0.        , 1.        , 0.66666667],
       [0.5       , 0.66666667, 0.33333333, 1.        , 0.        ,
        1.        , 0.6       , 0.        , 0.33333333, 0.33333333],
       [1.        , 0.8       , 0.75      , 1.        , 0.        ,
        1.        , 1.        , 0.66666667, 0.5       , 0.66666667],
       [1.        , 0.5       , 0.33333333, 0.5       , 1.        ,
        0.5       , 0.2       , 1.        , 1.        , 0.        ],
       [0.        , 0.75      , 0.33333333, 0.5       , 1.        ,
        0.5       , 0.2       , 0.        , 1.        , 0.66666667],
       [0.66666667, 0.33333333, 0.5       , 0.        , 1.        ,
        0.66666667, 0.33333333, 0.        , 1.        , 0.66666667],
       [0.5       , 0.66666667, 0.33333333, 1.        , 0.        ,
        1.        , 0.6       , 0.5       , 0.33333333, 0.33333333],
       [0.5       , 0.8       , 1.        , 1.        , 0.        ,
        1.        , 1.        , 0.66666667, 0.75      , 0.66666667],
       [1.        , 0.5       , 0.33333333, 0.83333333, 1.        ,
        0.5       , 0.4       , 1.        , 1.        , 0.        ],
       [0.        , 0.25      , 0.66666667, 0.66666667, 1.        ,
        0.        , 0.4       , 0.        , 1.        , 0.        ],
       [1.        , 1.        , 1.        , 0.33333333, 0.        ,
        1.        , 0.66666667, 0.        , 1.        , 0.66666667]])

In [24]:
output_results

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1.000000,0.9,0.900000,0.9,0.900000,0.90000,0.336950,0.9,0.90000,0.9,0.9,0.444911,0.900000,0.900000,0.641490
1,0.900000,1.0,0.900000,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
2,0.900000,0.9,1.000000,0.9,0.770198,0.90000,0.143439,0.9,0.90000,0.9,0.9,0.208068,0.866728,0.900000,0.390316
3,0.900000,0.9,0.900000,1.0,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
4,0.900000,0.9,0.770198,0.9,1.000000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
5,0.900000,0.9,0.900000,0.9,0.900000,1.00000,0.850640,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
6,0.336950,0.9,0.143439,0.9,0.900000,0.85064,1.000000,0.9,0.83455,0.9,0.9,0.900000,0.900000,0.561045,0.900000
7,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.900000,1.0,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
8,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.834550,0.9,1.00000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
9,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.900000,0.9,0.90000,1.0,0.9,0.900000,0.900000,0.900000,0.900000
10,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,1.0,0.900000,0.900000,0.900000,0.900000
11,0.444911,0.9,0.208068,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,1.000000,0.900000,0.657574,0.900000
12,0.900000,0.9,0.866728,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,1.000000,0.900000,0.900000
13,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.561045,0.9,0.90000,0.9,0.9,0.657574,0.900000,1.000000,0.850640
14,0.641490,0.9,0.390316,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.850640,1.000000

In [23]:
column_mapping = {}
for i, name in enumerate(list(eeg_type_dist.columns)):
    column_mapping[i] = name

row_mapping = {}
for i, name in enumerate(list(eeg_type_dist.columns)):
    row_mapping[i] = name
    
df = output_results.rename(columns=column_mapping, index=row_mapping)
df

,stat_onlyREM,stat_onlyN1,stat_onlyN2,stat_onlyN3,stat_onlyWake,pli_onlyREM,pli_onlyN1,pli_onlyN2,pli_onlyN3,pli_onlyWake,combinedREM,combinedN1,combinedN2,combinedN3,combinedWake
stat_onlyREM,1.000000,0.9,0.900000,0.9,0.900000,0.90000,0.336950,0.9,0.90000,0.9,0.9,0.444911,0.900000,0.900000,0.641490
stat_onlyN1,0.900000,1.0,0.900000,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
stat_onlyN2,0.900000,0.9,1.000000,0.9,0.770198,0.90000,0.143439,0.9,0.90000,0.9,0.9,0.208068,0.866728,0.900000,0.390316
stat_onlyN3,0.900000,0.9,0.900000,1.0,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
stat_onlyWake,0.900000,0.9,0.770198,0.9,1.000000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
pli_onlyREM,0.900000,0.9,0.900000,0.9,0.900000,1.00000,0.850640,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
pli_onlyN1,0.336950,0.9,0.143439,0.9,0.900000,0.85064,1.000000,0.9,0.83455,0.9,0.9,0.900000,0.900000,0.561045,0.900000
pli_onlyN2,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.900000,1.0,0.90000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
pli_onlyN3,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.834550,0.9,1.00000,0.9,0.9,0.900000,0.900000,0.900000,0.900000
pli_onlyWake,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.900000,0.9,0.90000,1.0,0.9,0.900000,0.900000,0.900000,0.900000
combinedREM,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,1.0,0.900000,0.900000,0.900000,0.900000
combinedN1,0.444911,0.9,0.208068,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,1.000000,0.900000,0.657574,0.900000
combinedN2,0.900000,0.9,0.866728,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,1.000000,0.900000,0.900000
combinedN3,0.900000,0.9,0.900000,0.9,0.900000,0.90000,0.561045,0.9,0.90000,0.9,0.9,0.657574,0.900000,1.000000,0.850640
combinedWake,0.641490,0.9,0.390316,0.9,0.900000,0.90000,0.900000,0.9,0.90000,0.9,0.9,0.900000,0.900000,0.850640,1.000000

### Mark